---
title: "test_Price_in_thousands"
author: 'The Principal Components - Ed Brown, Daphne Lin, Linh Tran, Lisa Wu '
date: "2022-07-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r check packages and install, include=FALSE}
if(!require("Hmisc")){install.packages('Hmisc')}
if(!require("funModeling")){install.packages('funModeling')}
if(!require("olsrr")){install.packages('olsrr')}
if(!require("ggpubr")){install.packages('ggpubr')}

```
```{r load packages and set options, include=FALSE}

library(tidyverse) 
library(stargazer)
library(sandwich)
library(lmtest)
library(Hmisc)
library(funModeling)
library(olsrr)
library(ggpubr)
library(moments)

theme_set(theme_bw())
```
```{r}
library(readr) 
car_sales <- read_csv("../datasets/Car_sales.csv", 
                       col_types = cols(Price_in_thousands = col_number(), 
                                        cylinders = col_number(), displacement = col_number(), 
                                        horsepower = col_number(), weight = col_number(), 
                                        acceleration = col_number()))
names(car_sales)
head(car_sales, 10)
```
```{r transform variables}
colnames(car_sales)[1] <- "manufacturer"
colnames(car_sales)[2] <- "model"
colnames(car_sales)[3] <- "sales_000"
colnames(car_sales)[4] <- "resale_value"
colnames(car_sales)[5] <- "vehicle_type"
colnames(car_sales)[6] <- "price_000"
colnames(car_sales)[7] <- "engine_size"
colnames(car_sales)[8] <- "horsepower"
colnames(car_sales)[9] <- "wheelbase"
colnames(car_sales)[10] <- "width"
colnames(car_sales)[11] <- "length"
colnames(car_sales)[12] <- "curb_weight"
colnames(car_sales)[13] <- "fuel_capacity"
colnames(car_sales)[14] <- "fuel_efficiency"
colnames(car_sales)[15] <- "latest_launch"
colnames(car_sales)[16] <- "power_perf"

head(car_sales,5)
car_sales <- car_sales[!(car_sales$model == "Town & Country"),]
car_sales <-car_sales[!is.na(car_sales$power_perf),]
car_sales <- car_sales %>%
  mutate(
    price_resale_diff = price_000-resale_value,
    ln_sales_000 = log(sales_000),                      # This approximates the % change in sales
    ln_price_000 = log(price_000),    # This approximates the % change in price
    ln_resale_value = log(resale_value),    # This approximates the % change in resale value
    ln_engine_size = log(engine_size),
    ln_horsepower = log(horsepower),        # This approximates the % change in horsepower
    ln_wheelbase = log(wheelbase),
    ln_width = log(width),
    ln_curb_weight = log(curb_weight),
    ln_fuel_capacity = log(fuel_capacity),
    ln_fuel_efficiency = log(fuel_efficiency),
    ln_power_perf = log(power_perf),
    ln_price_resale_diff = log(price_resale_diff),
    range = fuel_capacity * fuel_efficiency,
    volume = length * width,
    ln_volume = log(volume),
    density = curb_weight / volume,
    ln_density = log(density)
    )
#.6 R2, distribution looking good, then log,

car_sales$manufacturer <- as.factor(car_sales$manufacturer)
car_sales$model <- as.factor(car_sales$model)
car_sales$vehicle_type <- as.factor(car_sales$vehicle_type)
#Base model version is Luxury in the "my_category"
car_sales[,"my_category"] <- relevel(as.factor(car_sales$my_category), ref = "L")
```

```{r}
correlation_table(data=car_sales, target="price_000")
```

```{r}

A <- ggplot(car_sales, aes(x=price_000)) + geom_histogram(bins=60)
B <- ggplot(car_sales, aes(x=ln_price_000)) + geom_histogram(bins=60)

C <- ggplot(car_sales, aes(x=sales_000)) + geom_histogram(bins=60)
D <- ggplot(car_sales, aes(x=ln_sales_000)) + geom_histogram(bins=60)

E <- ggplot(car_sales, aes(x=resale_value)) + geom_histogram(bins=60)
F <- ggplot(car_sales, aes(x=ln_resale_value)) + geom_histogram(bins=60)

G <- ggplot(car_sales, aes(x=engine_size)) + geom_histogram(bins=60)
H <- ggplot(car_sales, aes(x=ln_engine_size)) + geom_histogram(bins=60)

I <- ggplot(car_sales, aes(x=horsepower)) + geom_histogram(bins=60)
J <- ggplot(car_sales, aes(x=ln_horsepower)) + geom_histogram(bins=60)

K <- ggplot(car_sales, aes(x=wheelbase)) + geom_histogram(bins=60)
L <- ggplot(car_sales, aes(x=ln_wheelbase)) + geom_histogram(bins=60)

M <- ggplot(car_sales, aes(x=width)) + geom_histogram(bins=60)
N <- ggplot(car_sales, aes(x=ln_width)) + geom_histogram(bins=60)

O <- ggplot(car_sales, aes(x=curb_weight)) + geom_histogram(bins=60)
P <- ggplot(car_sales, aes(x=ln_curb_weight)) + geom_histogram(bins=60)

Q <- ggplot(car_sales, aes(x=fuel_capacity)) + geom_histogram(bins=60)
R <- ggplot(car_sales, aes(x=ln_fuel_capacity)) + geom_histogram(bins=60)

S <- ggplot(car_sales, aes(x=fuel_efficiency)) +  geom_histogram(bins=60)
T <- ggplot(car_sales, aes(x=ln_fuel_efficiency)) +  geom_histogram(bins=60)

U <- ggplot(car_sales, aes(x=power_perf)) +  geom_histogram(bins=60)
V <- ggplot(car_sales, aes(x=ln_power_perf)) + geom_histogram(bins=60)

W <- ggplot(car_sales, aes(x=price_resale_diff)) + geom_histogram(bins=60)
X <- ggplot(car_sales, aes(x=ln_price_resale_diff)) + geom_histogram(bins=60)

```
```{r}
ggarrange(A, B, C, D, E, F, G, H + rremove("x.text"), 
          labels = c("A", "B", "C", "D", "E", "F", "G", "H"),
          ncol = 2, nrow = 4)
```
# Log transformation improves the distribution to be more normal for: Price, Sales, Resale and Engine Size


```{r}
ggarrange(I, J, K, L, M, N, O, P + rremove("x.text"), 
          labels = c("I", "J", "K", "L", "M", "N", "O", "P"),
          ncol = 2, nrow = 4)
```
```{r}
ggarrange(Q, R, S, T, U, V, W, X + rremove("x.text"), 
          labels = c("Q", "R", "S", "T", "U", "V", "W", "X"),
          ncol = 2, nrow = 4)
```
# From all graphs above, log transformation improves the distribution to be more normal for: Price, Sales, Resale, Engine Size, weight, width, horsepower, fuel capacility, fuel efficiency, power_perf

```{r}
Y <- ggplot(car_sales, aes(x=ln_horsepower, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)

Z <- ggplot(car_sales, aes(x=ln_power_perf, y=ln_price_000)) + geom_point()+ geom_smooth(method=lm)

AA <- ggplot(car_sales, aes(x=ln_fuel_efficiency, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)
AB <- ggplot(car_sales, aes(x=ln_curb_weight, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)
AC <- ggplot(car_sales, aes(x=ln_width, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)
AD <- ggplot(car_sales, aes(x=ln_fuel_capacity, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)
AE <- ggplot(car_sales, aes(x=ln_fuel_capacity, y=ln_fuel_efficiency)) +  geom_point()+ geom_smooth(method=lm)
AF <- ggplot(car_sales, aes(x=ln_curb_weight, y=ln_fuel_capacity)) +  geom_point()+ geom_smooth(method=lm)
```

```{r}
ggarrange(Y, Z, AA, AB, AC, AD, AE, AF + rremove("x.text"), 
          # labels = c("Y", "Z", "AA", "AB", "AC", "AD", "AE","AF"),
          ncol = 2, nrow = 4)
```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_base <- car_sales %>% lm(ln_price_000 ~ ln_power_perf, data = .)
car_price_base_se <- car_price_base %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_base, type="text",se = list(car_price_base_se))
coeftest(car_price_base, vconv = vcovHC(type = "HC1"))
plot(car_price_base)
lmtest::bptest(car_price_base)

```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_base2 <- car_sales %>% lm(ln_price_000 ~ ln_curb_weight, data = .)
car_price_base2_se <- car_price_base2 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_base2, type="text",se = list(car_price_base2_se))
coeftest(car_price_base2, vconv = vcovHC(type = "HC1"))
plot(car_price_base2)
lmtest::bptest(car_price_base2)
```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_base3 <- car_sales %>% lm(ln_price_000 ~ ln_horsepower, data = .)
car_price_base3_se <- car_price_base3 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_base3, type="text",se = list(car_price_base3_se))
coeftest(car_price_base3, vconv = vcovHC(type = "HC1"))
plot(car_price_base3)
lmtest::bptest(car_price_base3)
```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_base4 <- car_sales %>% lm(ln_price_000 ~ ln_engine_size, data = .)
car_price_base4_se <- car_price_base4 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_base4, type="text",se = list(car_price_base4_se))
coeftest(car_price_base4, vconv = vcovHC(type = "HC1"))
plot(car_price_base4)
lmtest::bptest(car_price_base4)
```
```{r compare base model 1 variable only}
stargazer(star.cutoffs = c(0.05, 0.01, 0.001),
          title = "Car Price Linear Regression One Variable Model Only",
          car_price_base, car_price_base2, car_price_base3, car_price_base4, type="text",
          covariate.labels = c("Power Performance", "Weight", "Horsepower","Engine Size"),
          se = list(car_price_base_se, car_price_base2_se, car_price_base3_se, car_price_base4_se))
```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_plus <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + ln_engine_size, data = .)
car_price_plus_se <- car_price_plus %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_plus, type="text",se = list(car_price_plus_se))
coeftest(car_price_plus, vconv = vcovHC(type = "HC1"))
plot(car_price_plus)
lmtest::bptest(car_price_plus)
fit_plus_vif = ols_vif_tol(car_price_plus)
fit_plus_vif
```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_sup <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + ln_engine_size + ln_curb_weight + ln_wheelbase, data = .)
car_price_sup_se <- car_price_sup %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_sup, type="text",se = list(car_price_sup_se))
coeftest(car_price_sup, vconv = vcovHC(type = "HC1"))
plot(car_price_sup)
lmtest::bptest(car_price_sup)
fit_sup_vif = ols_vif_tol(car_price_sup)
fit_sup_vif
```
```{r}
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
plot(1,main=1)
plot(2,main=2)
plot(3,main=3)
plot(4,main=4)
car_price_plus2 <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + ln_engine_size + ln_fuel_efficiency, data = .)
car_price_plus2_se <- car_price_plus2 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_price_plus2, type="text",se = list(car_price_plus2_se))
coeftest(car_price_plus2, vconv = vcovHC(type = "HC1"))
plot(car_price_plus2)
lmtest::bptest(car_price_plus2)
fit_plus2_vif = ols_vif_tol(car_price_plus2)
fit_plus2_vif
```


```{r  test data linear model results, warning=FALSE}
stargazer(star.cutoffs = c(0.05, 0.01, 0.001),
          title = "Car Price Linear Regression",
          car_price_base, car_price_plus, car_price_plus2, car_price_sup, type="text",
          covariate.labels = c("Power Performance", "Engine Size", "Fuel Efficiency", "Car Weight","Wheel Base"),
          se = list(car_price_base_se, car_price_plus_se, car_price_plus2_se, car_price_sup_se))
```

```{r, test data linear model results, warning=FALSE}

model_1 = lm(ln_price_000 ~ ln_fuel_efficiency + power_perf + ln_engine_size, data = car_sales)
model_1

stargazer(model_1, star.cutoffs = c(0.05, 0.01, 0.001),
          title = "Car Price Linear Regression",
          model_1,  
          type = 'text',
          covariate.labels = c("Fuel Efficiency", "Power Performance","Engine Size")
)

res<- resid(model_1)
plot(fitted(model_1), res)
abline(0,0)

```
```{r}
#Proposed Base Model ED
car_base_ed <- car_sales %>% lm(ln_price_000 ~ ln_power_perf, data = .)
car_base_ed_se <- car_base_ed %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_ed, type="text",se = list(car_base_ed_se))
coeftest(car_base_ed, vconv = vcovHC(type = "HC1"))
plot(car_base_ed)
lmtest::bptest(car_base_ed)
#ols_vif_tol(car_base_ed)
```
```{r}
##Proposed Second Model ED
car_base_cat_ed <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + ln_volume, data = .)
car_base_cat_ed_se <- car_base_cat_ed %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_cat_ed, type="text",se = list(car_base_cat_ed_se))
coeftest(car_base_cat_ed, vconv = vcovHC(type = "HC1"))
plot(car_base_cat_ed)
lmtest::bptest(car_base_cat_ed)
ols_vif_tol(car_base_cat_ed)
```
```{r model}
## Proposed Third Model (Ed)
car_base_manu_ed <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + my_category + ln_volume, data = .)
car_base_manu_ed_se <- car_base_manu_ed %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_manu_ed, type="text",se = list(car_base_manu_ed_se))
coeftest(car_base_manu_ed, vconv = vcovHC(type = "HC1"))
plot(car_base_manu_ed)
lmtest::bptest(car_base_manu_ed)
ols_vif_tol(car_base_manu_ed)
```
```{r}
car_base_manu_ed <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + my_category + ln_density, data = .)
car_base_manu_ed_se <- car_base_manu_ed %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_manu_ed, type="text",se = list(car_base_manu_ed_se))
coeftest(car_base_manu_ed, vconv = vcovHC(type = "HC1"))
plot(car_base_manu_ed)
lmtest::bptest(car_base_manu_ed)
ols_vif_tol(car_base_manu_ed)
```

```{r}
car_base_brand <- car_sales %>% lm(ln_price_000 ~ ln_power_perf + my_category, data = .)
car_base_brand_se <- car_base_brand %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_brand, type="text",se = list(car_base_brand_se))
coeftest(car_base_brand, vconv = vcovHC(type = "HC1"))
plot(car_base_brand)
lmtest::bptest(car_base_brand)
VIF_brand <- ols_vif_tol(car_base_brand)
VIF_brand
```
```{r}
# category_hist <- hist(car_sales$my_category)
power_price_catogory <- ggplot(car_sales, aes(x=ln_power_perf, y=ln_price_000, color = my_category)) +  geom_point()+ geom_smooth(method=lm)
power_price <- ggplot(car_sales, aes(x=ln_power_perf, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)
power_sqrt_price <- ggplot(car_sales, aes(x=power_perf_sqrt, y=ln_price_000)) +  geom_point()+ geom_smooth(method=lm)
power_sqrt_price_catogory <- ggplot(car_sales, aes(x=power_perf_sqrt, y=ln_price_000, color = my_category)) +  geom_point()+ geom_smooth(method=lm)
power_price_catogory | power_price
power_sqrt_price_catogory | power_sqrt_price
```
```{r, warning=FALSE}
power_price_manu <- ggplot(car_sales_final, aes(x=ln_power_perf_sq, y=ln_price_000, color = manufacturer)) +  geom_point()+ geom_smooth(method=lm)
power_price_manu
```
```{r}
car_sales_final <- car_sales %>%  
  mutate(car_base_cat_residuals = resid(car_base_cat),
         car_base_cat_fitted = fitted(car_base_cat),
         ln_power_perf_sq = ln_power_perf ^ 2,
         ln_power_perf_sqrt = ln_power_perf ^ 0.5,
         power_perf_sqrt = power_perf ^ 0.5)


car_base_cat <- car_sales_final %>% lm(ln_price_000 ~  ln_power_perf + my_category, data = .)
car_base_cat_se <- car_base_cat %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_cat, type="text",se = list(car_base_cat_se))
coeftest(car_base_cat, vconv = vcovHC(type = "HC1"))
plot(car_base_cat)
lmtest::bptest(car_base_cat)
VIF_cat <- ols_vif_tol(car_base_cat)
VIF_cat
```

```{r}
U <- ggplot(car_sales_final, aes(x=power_perf)) +  geom_histogram(bins=60)
V <- ggplot(car_sales_final, aes(x=ln_power_perf)) + geom_histogram(bins=60)
V2 <- ggplot(car_sales_final, aes(x=ln_power_perf_sq)) + geom_histogram(bins=60)
V3 <- ggplot(car_sales_final, aes(x=power_perf_sqrt)) + geom_histogram(bins=60)
ggarrange(U, V, V2, V3 + rremove("x.text"), 
          # labels = c( "B", "C", "D", "E", "F", "G", "H"),
          ncol = 2, nrow = 2)
skewness_power_perf <- skewness(car_sales_final$power_perf)
skewness_ln_power_perf <- skewness(car_sales_final$ln_power_perf)
skewness_ln_power_perf_sq <- skewness(car_sales_final$ln_power_perf_sq)
skewness_power_perf
skewness_ln_power_perf
skewness_ln_power_perf_sq
```


```{r}

plot_1 <- car_sales_final %>%
  ggplot(aes(x = ln_power_perf, y = car_base_cat_residuals)) +
  geom_point() + geom_smooth(method = 'lm')

plot_2 <- car_sales_final %>%
  ggplot(aes(x = car_base_cat_fitted, y = car_base_cat_residuals)) +
  geom_point() + stat_smooth(se = TRUE)

plot_1 | plot_2

```


```{r}
car_base_power <- car_sales_final %>% lm(ln_price_000 ~ ln_power_perf_sq, data = .)
car_base_power_se <- car_base_cat %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(car_base_power, type="text",se = list(car_base_power_se))
coeftest(car_base_power, vconv = vcovHC(type = "HC1"))
plot(car_base_power)
lmtest::bptest(car_base_power)
# VIF_power <- ols_vif_tol(car_base_power)
# VIF_power
```

```{r}
car_sales_final <- car_sales_final %>%  
  mutate(car_base_power_residuals = resid(car_base_power),
         car_base_power_fitted = fitted(car_base_power))
                                
plot_3 <- car_sales_final %>%
  ggplot(aes(x = ln_power_perf_sqrt, y = car_base_power_residuals)) +
  geom_point() + geom_smooth(method = 'lm')

plot_4 <- car_sales_final %>%
  ggplot(aes(x = car_base_power_fitted, y = car_base_power_residuals)) +
  geom_point() + stat_smooth(se = TRUE)

plot_3 | plot_4

```

