---
title: "Crime_Dataset_EDA"
author: "the_principal_components"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r check packages and install, include=FALSE}
if(!require("Hmisc")){install.packages('Hmisc')}
if(!require("funModeling")){install.packages('funModeling')}
```
```{r load packages and set options, include=FALSE}

library(tidyverse) 
library(stargazer)
library(sandwich)
library(lmtest)
library(Hmisc)
library(funModeling)
library(olsrr)

theme_set(theme_bw())
```

```{r load data, message = FALSE, include=FALSE}
communities <- read.csv("../datasets/communities_with_headers.csv",  header = TRUE)
#communities <- read.arff("../datasets/communities.arff")
```

```{r check correlations}
correlation_table(data=communities, target="ViolentCrimesPerPop")
```
```{r}
communities <- communities %>% 
  mutate(ViolentCrimes_count = ViolentCrimesPerPop * population)

communities <- communities %>% 
mutate(ln_ViolentCrimes_count = log(ViolentCrimes_count))

communities <- communities %>% 
mutate(Illeg_count = PctIlleg * population)

communities <- communities %>% 
mutate(ln_Illeg_count = log(Illeg_count))

communities <- communities %>% 
mutate(PopUnderPov_count = PctPopUnderPov * population)

communities <- communities %>% 
mutate(ln_PopUnderPov_count = log(PopUnderPov_count))

# communities <- communities %>% 
# mutate(Fam2Par_count = PctFam2Par * population)
# 
# communities <- communities %>% 
# mutate(ln_Fam2Par_count = log(Fam2Par_count))

ggplot(communities, aes(x=PctIlleg, y=ln_ViolentCrimes_count)) + 
  geom_point()+
  geom_smooth(method=lm)

# summary(communities$ViolentCrimesPerPop)
# subset(communities,communities$ViolentCrimesPerPop==0)
communities_2 <- communities %>%
  subset(ViolentCrimes_count>0 ) %>% 
  subset(Illeg_count>0) %>% 
  subset(HousVacant>0) %>% 
  subset(PopUnderPov_count>0) %>% 
  subset(Fam2Par_count>0)

# summary(communities_2$ViolentCrimesPerPop)
summary(communities_2$PctIlleg)
ggplot(communities_2, aes(x=PctIlleg, y=ln_ViolentCrimes_count)) + 
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities_2, aes(x=ln_Illeg_count, y=ln_ViolentCrimes_count)) + 
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities_2, aes(x=ln_PopUnderPov_count, y=ln_ViolentCrimes_count)) + 
  geom_point()+
  geom_smooth(method=lm)

ggplot(communities_2, aes(x=ln_Illeg_count, y=ln_PopUnderPov_count)) + 
  geom_point()+
  geom_smooth(method=lm)
```


```{r plots positive correlation, message = FALSE, include=FALSE}
ggplot(communities, aes(x=PctIlleg, y=ViolentCrimesPerPop)) + 
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=pctWPubAsst, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctPopUnderPov, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctUnemployed, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=racepctblack, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctVacantBoarded, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctHousNoPhone, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=FemalePctDiv, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctLargHouseFam, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=TotalPctDiv, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctPolicBlack, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctPolicMinor, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=MalePctDivorce, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=NumIlleg, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctLargHouseOccup, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctWOFullPlumb, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
```
```{r plots negative correlation, message = FALSE, include=FALSE}
ggplot(communities, aes(x=medFamInc, y=ViolentCrimesPerPop)) + 
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=pctWInvInc, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=racePctWhite, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctYoungKids2Par, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctFam2Par, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctTeen2Par, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctKids2Par, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
```
```{r plots selected variables}
ggplot(communities, aes(x=PctPopUnderPov, y=ViolentCrimesPerPop)) + 
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctPopUnderPov)) + 
  geom_histogram(bins=60)
ggplot(communities, aes(x=TotalPctDiv, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=TotalPctDiv)) + 
  geom_histogram(bins=60)
ggplot(communities, aes(x=PolicPerPop, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PolicPerPop)) + 
  geom_histogram(bins=60)
ggplot(communities, aes(x=PctFam2Par, y=ViolentCrimesPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=PctFam2Par)) + 
  geom_histogram(bins=60)
ggplot(communities, aes(x=medFamInc, y=PolicPerPop)) +
  geom_point()+
  geom_smooth(method=lm)
ggplot(communities, aes(x=medFamInc)) + 
  geom_histogram(bins=60)

ggplot(communities, aes(x=perCapInc)) + 
  geom_histogram(bins=60)
ggplot(communities, aes(x=ViolentCrimesPerPop)) + 
  geom_histogram(bins=60)
ggplot(communities, aes(x=population)) + 
  geom_histogram(bins=60)
```
```{r fits }
crime_fit_01 <- communities %>% lm(ViolentCrimesPerPop ~ PctIlleg + HousVacant + PctUnemployed + NumStreet + TotalPctDiv, data = .)
crime_fit_01_se <- crime_fit_01 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(crime_fit_01, type="text",se = list(crime_fit_01_se))
coeftest(crime_fit_01, vconv = vcovHC(type = "HC1"))
fit_o1_vif = ols_vif_tol(crime_fit_01)
plot(crime_fit_01)
lmtest::bptest(crime_fit_01)
fit_o1_vif
```
```{r}
# crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ PctIlleg + HousVacant + PctUnemployed + NumStreet + TotalPctDiv, data = .)
# crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ PctIlleg + TotalPctDiv, data = .)
crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ ln_Illeg_count, data = .)
crime_fit_02_se <- crime_fit_02 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(crime_fit_02, type="text",se = list(crime_fit_02_se))
coeftest(crime_fit_02, vconv = vcovHC(type = "HC1"))
plot(crime_fit_02)
lmtest::bptest(crime_fit_02)
```
```{r}
# crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ PctIlleg + HousVacant + PctUnemployed + NumStreet + TotalPctDiv, data = .)
# crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ PctIlleg + TotalPctDiv, data = .)
crime_fit_03 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ ln_Illeg_count + ln_PopUnderPov_count, data = .)
crime_fit_03_se <- crime_fit_03 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(crime_fit_03, type="text",se = list(crime_fit_03_se))
coeftest(crime_fit_03, vconv = vcovHC(type = "HC1"))
plot(crime_fit_03)
lmtest::bptest(crime_fit_03)
```
```{r}
# crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ PctIlleg + HousVacant + PctUnemployed + NumStreet + TotalPctDiv, data = .)
# crime_fit_02 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ PctIlleg + TotalPctDiv, data = .)
crime_fit_04 <- communities_2 %>% lm(ln_ViolentCrimes_count ~ ln_PopUnderPov_count, data = .)
crime_fit_04_se <- crime_fit_04 %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(crime_fit_04, type="text",se = list(crime_fit_03_se))
coeftest(crime_fit_04, vconv = vcovHC(type = "HC1"))
plot(crime_fit_04)
lmtest::bptest(crime_fit_04)
```

