---
title: "Fuel Economy Gov Dataset EDA"
author: "the_principal_components"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r check packages and install, include=FALSE}
if(!require("Hmisc")){install.packages('Hmisc')}
if(!require("funModeling")){install.packages('funModeling')}
```
```{r load packages and set options, include=FALSE}

library(tidyverse) 
library(stargazer)
library(sandwich)
library(lmtest)
library(Hmisc)
library(funModeling)
library(olsrr)

theme_set(theme_bw())
```

```{r load data, message = FALSE, include=FALSE}
mpg <- read.csv("../datasets/vehicles.csv",  header = TRUE)
```


```{r}
mpg$tCharger[mpg$tCharger == "T"] <- TRUE
fix_cols <- c("tCharger")
tmp_mpg <- mpg[fix_cols]
tmp_mpg[is.na(tmp_mpg)] <- FALSE
mpg[fix_cols] <- tmp_mpg
rm(tmp_mpg, fix_cols)
mpg$sCharger[mpg$sCharger == "S"] <- TRUE
mpg$sCharger[mpg$sCharger != TRUE] <- FALSE
mpg <- mpg %>% mutate( 
  my_trans = case_when(
            grepl("Automatic", trany) ~ "Automatic",
            grepl("Manual", trany) ~ "Manual")
  , .before = 1)

mpg <- mpg %>% mutate( 
  ln_comb08U = log(comb08U),
  ln_displ = log(displ)
)
  
mpg <- mpg %>% mutate( 
  my_class = case_when(
            grepl("Two Seaters", VClass) ~ "LG",
            grepl("Minicompact Cars", VClass) ~ "XS",
            grepl("Subcompact Cars", VClass) ~ "XS",
            grepl("Compact Cars", VClass) ~ "SM",
            grepl("Midsize Cars", VClass) ~ "SM",
            grepl("Large Cars", VClass) ~ "MD",
            grepl("Small Station Wagons", VClass) ~ "MD",
            grepl("Mid-Size Cars Station Wagons", VClass) ~ "LG",
            grepl("Large Cars Station Wagons", VClass) ~ "LG",
            grepl("Small Pickup Trucks 2WD", VClass) ~ "LG",
            grepl("Small Pickup Trucks 4WD", VClass) ~ "LG",
            grepl("Small Sport Utility Vehicle 2WD", VClass) ~ "LG",
            grepl("Small Sport Utility Vehicle 4WD", VClass) ~ "LG",
            grepl("Midsize Station Wagons", VClass) ~ "LG",
            grepl("Minivan - 2WD", VClass) ~ "LG",
            grepl("Minivan - 4WD", VClass) ~ "LG",
            grepl("Special Purpose Vehicle 2WD", VClass) ~ "XL",
            grepl("Special Purpose Vehicle 4WD", VClass) ~ "XL",
            grepl("Standard Pickup Trucks 2WD", VClass) ~ "XL",
            grepl("Standard Pickup Trucks 4WD", VClass) ~ "XL",
            grepl("Standard Sport Utility Vehicle 2WD", VClass) ~ "XL",
            grepl("Standard Sport Utility Vehicle 4WD", VClass) ~ "XL",
            grepl("Vans, Passenger Type", VClass) ~ "XL",
            )
  , .before = 1)
mpg$my_trans <- as.factor(mpg$my_trans)
mpg$my_class <- as.factor(mpg$my_class)
mpg$drive <- as.factor(mpg$drive)
mpg$VClass <- as.factor(mpg$VClass)
mpg$startStop <- as.factor(mpg$startStop)
final_mpg_dataset <- dplyr::filter(mpg, year == 2018 &  (fuelType1 != "Diesel" & fuelType1 != "Electricity"))

```

```{r check correlations}
correlation_table(data=final_mpg_dataset, target="comb08U")
```
\newpage
```{r}
ggplot(final_mpg_dataset, aes(x=displ, y=comb08U)) +
  geom_point()+
  geom_smooth(method=lm)
```
\newpage
```{r}
ggplot(final_mpg_dataset, aes(x=displ)) + 
  geom_histogram(bins=20)
```
\newpage
```{r}
ggplot(final_mpg_dataset, aes(x=startStop, y=comb08U)) +
  geom_boxplot(notch=TRUE, outlier.colour="red", outlier.shape=8)
```
\newpage
```{r}
ggplot(final_mpg_dataset, aes(x=tCharger, y=comb08U)) +
  geom_boxplot(notch=TRUE, outlier.colour="red", outlier.shape=8)
```
\newpage
```{r}
ggplot(final_mpg_dataset, aes(x=sCharger, y=comb08U)) +
  geom_boxplot(notch=TRUE, outlier.colour="red", outlier.shape=8)
```
\newpage
```{r}
ggplot(final_mpg_dataset, aes(x=my_class , y=comb08U)) +
  geom_boxplot(notch=TRUE, outlier.colour="red", outlier.shape=8)
```
\newpage
```{r}
## 30% of the sample size
smp_size <- floor(0.30 * nrow(final_mpg_dataset))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(final_mpg_dataset)), size = smp_size)

train_mpg <- final_mpg_dataset[train_ind, ]
test_mpg <- final_mpg_dataset[-train_ind, ]
rm(smp_size, train_ind)
```

\newpage
```{r mpg base model }
mpg_base_model <- final_mpg_dataset %>% lm(ln_comb08U ~ ln_displ + startStop, data = .)
mpg_base_model_se <- mpg_base_model %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(mpg_base_model, type="text",se = list(mpg_base_model_se))
coeftest(mpg_base_model, vconv = vcovHC(type = "HC1"))
#ols_vif_tol(mpg_base_model)
plot(mpg_base_model)
lmtest::bptest(mpg_base_model)
```
\newpage
```{r mpg base startstop model }
mpg_base_induction_model <- final_mpg_dataset %>% lm(ln_comb08U ~ ln_displ + startStop + tCharger + sCharger, data = .)
mpg_base_induction_model_se <- mpg_base_induction_model %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(mpg_base_induction_model, type="text",se = list(mpg_base_induction_model_se))
coeftest(mpg_base_induction_model, vconv = vcovHC(type = "HC1"))
ols_vif_tol(mpg_base_induction_model)
plot(mpg_base_induction_model)
lmtest::bptest(mpg_base_induction_model)
```
\newpage
```{r mpg base induction class model }
mpg_base_induction_class_model <- final_mpg_dataset %>% lm(ln_comb08U ~ ln_displ + startStop + tCharger + sCharger + my_class, data = .)
mpg_base_induction_class_model_se <- mpg_base_induction_class_model %>% vcovHC(type = "HC1") %>% diag() %>% sqrt()
stargazer(mpg_base_induction_class_model, type="text",se = list(mpg_base_induction_class_model_se))
coeftest(mpg_base_induction_class_model, vconv = vcovHC(type = "HC1"))
ols_vif_tol(mpg_base_induction_class_model)
plot(mpg_base_induction_class_model)
lmtest::bptest(mpg_base_induction_class_model)
```